"""Shareable simulation package for JIT QEC benchmark generation.

Layout: model-independent machinery (geometry.py, lattice.py, decoder.py,
runner.py) plus one module per model (twisted.py + TQD_runner.py for the
twisted quantum double). runner.py is the general layered data generator;
TQD_runner.py is the original two-layer twisted quantum double driver.
"""

from .geometry import (
    DIMENSIONS,
    get_time_depth,
    last_time_step_measurement_edges,
    vertex_index,
)
from .lattice import (
    build_edge_endpoints,
    build_incidence_matrix,
    build_neighbor_edge_lookup,
    cluster_edge_indices,
    cluster_ends,
    edge_clusters,
    shift_edges_one_step,
)
from .decoder import (
    CommitFunction,
    CommitRejected,
    classic_commit,
    constant_speed_commit,
    count_nontrivial_loops,
    is_logical_error_z2,
    jit_decode_full,
    jit_decode_step,
    make_constant_speed_commit,
    z2_logical_error,
)
from .twisted import (
    COLORS,
    build_z_correction_matchings_from_x,
    completing_the_loop_herald,
    generate_twisted_z_errors,
    get_vertex_edges,
    make_twisted_layer_specs,
    precompute_twist_masks,
    twisted_delegated_errors,
)
from .runner import (
    ChannelSpec,
    LayerSpec,
    LayerView,
    SimulationContext,
    build_context,
    build_run_filename,
    decode_channel,
    run_layered_simulation,
    run_physical_error_sweep,
    run_repetition,
    sample_physical_errors,
)
from .TQD_runner import (
    build_result_filename,
    run_full_simulation,
    run_x_only_simulation,
)
from .multilayer import (
    MultiLayerContext,
    ParentLayerView,
    build_multilayer_context,
    build_multilayer_filename,
    estimate_threshold,
    jit_decode_step_weighted,
    layer_has_logical_error,
    make_default_layer_specs,
    make_toric_layer_specs,
    plot_toric_delegation_study,
    run_global_cascade,
    run_multilayer_jit,
    run_multilayer_simulation,
    run_toric_delegation_study,
    sample_base_noises,
    slice_edge_time,
    toric_delegated_accountant,
    toric_delegated_generator,
    twisted_delegated_accountant,
    twisted_delegated_generator,
)

__all__ = [
    "DIMENSIONS",
    "get_time_depth",
    "last_time_step_measurement_edges",
    "vertex_index",
    "build_edge_endpoints",
    "build_incidence_matrix",
    "build_neighbor_edge_lookup",
    "cluster_edge_indices",
    "cluster_ends",
    "edge_clusters",
    "shift_edges_one_step",
    "CommitFunction",
    "CommitRejected",
    "classic_commit",
    "constant_speed_commit",
    "count_nontrivial_loops",
    "is_logical_error_z2",
    "jit_decode_full",
    "jit_decode_step",
    "make_constant_speed_commit",
    "z2_logical_error",
    "COLORS",
    "build_z_correction_matchings_from_x",
    "completing_the_loop_herald",
    "generate_twisted_z_errors",
    "get_vertex_edges",
    "make_twisted_layer_specs",
    "precompute_twist_masks",
    "twisted_delegated_errors",
    "ChannelSpec",
    "LayerSpec",
    "LayerView",
    "SimulationContext",
    "build_context",
    "build_run_filename",
    "decode_channel",
    "run_layered_simulation",
    "run_physical_error_sweep",
    "run_repetition",
    "sample_physical_errors",
    "build_result_filename",
    "run_full_simulation",
    "run_x_only_simulation",
    "MultiLayerContext",
    "ParentLayerView",
    "build_multilayer_context",
    "build_multilayer_filename",
    "estimate_threshold",
    "jit_decode_step_weighted",
    "layer_has_logical_error",
    "make_default_layer_specs",
    "make_toric_layer_specs",
    "plot_toric_delegation_study",
    "run_global_cascade",
    "run_multilayer_jit",
    "run_multilayer_simulation",
    "run_toric_delegation_study",
    "sample_base_noises",
    "slice_edge_time",
    "toric_delegated_accountant",
    "toric_delegated_generator",
    "twisted_delegated_accountant",
    "twisted_delegated_generator",
]
